;; This "home-environment" file can be passed to 'guix home reconfigure'
;; to reproduce the content of your profile.  This is "symbolic": it only
;; specifies package names.  To reproduce the exact same profile, you also
;; need to capture the channels being used, as returned by "guix describe".
;; See the "Replicating Guix" section in the manual.

(use-modules
  (gnu home)
  (gnu packages)
  (gnu services)
  (guix gexp)
  (gnu home services shells)
  (awb99 guixutils) 
  (awb99 config helper)
)

(define (specifications->package specs)
(map specification->package specs))

(home-environment
  (packages
    (->packages-output ; ->packages ; map specification->package
         (list "libreoffice"
               "emacs"
               "icecat"
               "ungoogled-chromium"
               "nyxt"
               "docker"
               "qemu"
               "virt-manager"
               "udiskie"
               "remmina"
               "claws-mail"
               "java-swt"
               "emacs-spacemacs-theme"
               "openssh"
               "openjdk:jdk"
               "gparted"
               "inxi"
               "git"
               "certbot"
               "telegram-desktop"
               "quassel"
               "xfce4-screenshooter"
               "xfce4-notifyd"
               "xfce4-whiskermenu-plugin"
               "exo"
               "fontconfig"
               "eovim"
               "kate"
               "mousepad"
               "pdfarranger"
               "qpdfview"
               "midori"
               "nomad"
               "vimb"
               "glimpse"
               "xdot"
               "gst-libav"
               "gst-plugins-base"
               "gst-plugins-good"
               "gst-plugins-bad"
               "gst-plugins-ugly"
               "vlc"
               "kodi"
               "ffmpeg"
               "pavucontrol"
               "keepassxc"
               "transmission:gui"
               "qbittorrent"
               "youtube-dl"
               "syncthing-gtk"
               "docker-compose"
               "flatpak"
               "catfish"
               "celestia-gtk"
               "syncthing"
               "elementary-xfce-icon-theme"
               "adwaita-icon-theme"
               "breeze-icons"
               "matcha-theme"
               "papirus-icon-theme"
               "java-qdox"
               "iputils"
               "fish"
               "byobu"
               "wget"
               "curl"
               "unzip"
               "ranger"
               "mc"
               "glances"
               "rsync"
               "mesa-utils"
               "openssl"
               "xclock"
               "sxiv"
               "gstreamer"
               "subdl"
               "libwebp"
               "xdotool"
               "vscodium"
               "ntp"
               "xsettingsd"
               "font-iosevka"
               "font-iosevka-aile"
               "node"
               "graphviz"
               "sdparm"
               "hdparm"
               "parted"
               "cryptsetup"
               "cpuid"
               "cpuinfo"
               "tree"
               "whois"
               "perftest"
               "the-silver-searcher"
               "bash"
               "zsh"
               "zsh-autosuggestions"
               "less"
               "which"
               "grep"
               "sed"
               "tmux"
               "tar"
               "p7zip"
               "tarlz"
               "gzip"
               "zip"
               "sysfsutils"
               "htop"
               "ncdu"
               "ncurses"
               "rclone"
               "nano"
               "findutils"
               "mlocate"
               "glibc-locales"
               "mcron"
               "fasd"
               "coreutils"
               "hello"
               "make"
               "gcc-toolchain"
               "xcursor-themes"
               "hicolor-icon-theme"
               "font-hack"
               "font-fira-mono"
               "font-gnu-unifont"
               "font-google-noto"
               "font-openmoji"
               "opus"
               "docker-cli"
               "scm"
               "go-ipfs"
               "arc-icon-theme"
               "gnome-icon-theme"
               "gnome-backgrounds"
               "font-fira-code"
               "font-jetbrains-mono"
               "font-abattis-cantarell"
               "font-dejavu"
               "font-gnu-freefont"
               "font-liberation"
               "font-awesome"
               "font-google-material-design-icons"
               "gs-fonts"
               "font-ibm-plex"
               "font-wqy-microhei"
               "fastjar"
               "rlwrap"
               "clojure-tools"
               "leiningen"
               "babashka")))
  (services
    (list (service
            home-bash-service-type
            (home-bash-configuration
              (aliases
                '(("grep='grep --color" . "auto")
                  ("ll" . "ls -l")
                  ("ls='ls -p --color" . "auto")))
              (bashrc
                (list (local-file "./.bashrc" "bashrc")))
              (bash-profile
                (list (local-file
                        "./.bash_profile"
                        "bash_profile"))))))))
